[project]
name = "tictactoe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colorama>=0.4.6",
    "pyinstaller>=6.15.0",
    "wcwidth>=0.2.13",
]
